local emoji = {
	{["Name"] = ":eyes:",						["Emoji"] = "👀"},
	{["Name"] = ":eye:",						["Emoji"] = "👁"},
	{["Name"] = ":speaking head:",				["Emoji"] = "🗣"},
	{["Name"] = ":bust in silhouette:",			["Emoji"] = "👤"},
	{["Name"] = ":busts in silhouette:",		["Emoji"] = "👥"},
	{["Name"] = ":dog face:",					["Emoji"] = "🐶"},
	{["Name"] = ":cat face:",					["Emoji"] = "🐱"},
	{["Name"] = ":rabbit:",						["Emoji"] = "🐇"},
	{["Name"] = ":sunflower:",					["Emoji"] = "🌻"},
	{["Name"] = ":blossom:",					["Emoji"] = "🌼"},
	{["Name"] = ":tulip:",						["Emoji"] = "🌷"},
	{["Name"] = ":evergreen tree:",				["Emoji"] = "🌲"},
	{["Name"] = ":deciduous tree:",				["Emoji"] = "🌳"},
	{["Name"] = ":four leaf clover:",			["Emoji"] = "🍀"},
	{["Name"] = ":maple leaf:",					["Emoji"] = "🍁"},
	{["Name"] = ":fallen leaf:",				["Emoji"] = "🍂"},
	{["Name"] = ":leaf fluttering in wind:",	["Emoji"] = "🍃"},
	{["Name"] = ":mushroom:",					["Emoji"] = "🍄"},
	{["Name"] = ":watermelon:",					["Emoji"] = "🍉"},
	{["Name"] = ":bread:",						["Emoji"] = "🍞"},
	{["Name"] = ":hamburger:",					["Emoji"] = "🍔"},
	{["Name"] = ":egg:",						["Emoji"] = "🥚"},
	{["Name"] = ":spaghetti:",					["Emoji"] = "🍝"},
	{["Name"] = ":candy:",						["Emoji"] = "🍬"},
	{["Name"] = ":hot beverage:",				["Emoji"] = "☕"},
	{["Name"] = ":beer mug:",					["Emoji"] = "🍺"},
	{["Name"] = ":ice:",						["Emoji"] = "🧊"},
	{["Name"] = ":globe with meridians:",		["Emoji"] = "🌐"},
	{["Name"] = ":world map:",					["Emoji"] = "🗺"},
	{["Name"] = ":compass:",					["Emoji"] = "🧭"},
	{["Name"] = ":mountain:",					["Emoji"] = "⛰"},
	{["Name"] = ":camping:",					["Emoji"] = "🏕"},
	{["Name"] = ":beach with umbrella:",		["Emoji"] = "🏖"},
	{["Name"] = ":brick:",						["Emoji"] = "🧱"},
	{["Name"] = ":house:",						["Emoji"] = "🏠"},
	{["Name"] = ":ferris wheel:",				["Emoji"] = "🎡"},
	{["Name"] = ":barber pole:",				["Emoji"] = "💈"},
	{["Name"] = ":circus tent:",				["Emoji"] = "🎪"},
	{["Name"] = ":automobile:",					["Emoji"] = "🚗"},
	{["Name"] = ":motorcycle:",					["Emoji"] = "🏍"},
	{["Name"] = ":fuel pump:",					["Emoji"] = "⛽"},
	{["Name"] = ":stop sign:",					["Emoji"] = "🛑"},
	{["Name"] = ":anchor:",						["Emoji"] = "⚓"},
	{["Name"] = ":ring buoy:",					["Emoji"] = "🛟"},
	{["Name"] = ":canoe:",						["Emoji"] = "🛶"},
	{["Name"] = ":airplane:",					["Emoji"] = "✈"},
	{["Name"] = ":helicopter:",					["Emoji"] = "🚁"},
	{["Name"] = ":rocket:",						["Emoji"] = "🚀"},
	{["Name"] = ":flying saucer:",				["Emoji"] = "🛸"},
	{["Name"] = ":hourglass done:",				["Emoji"] = "⌛"},
	{["Name"] = ":three o’clock:",				["Emoji"] = "🕒"},
	{["Name"] = ":new moon:",					["Emoji"] = "🌑"},
	{["Name"] = ":full moon:",					["Emoji"] = "🌕"},
	{["Name"] = ":crescent moon:",				["Emoji"] = "🌙"},
	{["Name"] = ":sun:",						["Emoji"] = "☀"},
	{["Name"] = ":ringed planet:",				["Emoji"] = "🪐"},
	{["Name"] = ":star:",						["Emoji"] = "⭐"},
	{["Name"] = ":glowing star:",				["Emoji"] = "🌟"},
	{["Name"] = ":milky:",						["Emoji"] = "🌌"},
	{["Name"] = ":cyclone:",					["Emoji"] = "🌀"},
	{["Name"] = ":rainbow:",					["Emoji"] = "🌈"},
	{["Name"] = ":umbrella:",					["Emoji"] = "☂"},
	{["Name"] = ":high voltage:",				["Emoji"] = "⚡"},
	{["Name"] = ":snowflake:",					["Emoji"] = "❄"},
	{["Name"] = ":snowman:",					["Emoji"] = "⛄"},
	{["Name"] = ":comet:",						["Emoji"] = "☄"},
	{["Name"] = ":fire:",						["Emoji"] = "🔥"},
	{["Name"] = ":droplet:",					["Emoji"] = "💧"},
	{["Name"] = ":jack-o-lantern:",				["Emoji"] = "🎃"},
	{["Name"] = ":Christmas tree:",				["Emoji"] = "🎄"},
	{["Name"] = ":fireworks:",					["Emoji"] = "🎆"},
	{["Name"] = ":sparkler:",					["Emoji"] = "🎇"},
	{["Name"] = ":firecracker:",				["Emoji"] = "🧨"},
	{["Name"] = ":sparkles:",					["Emoji"] = "✨"},
	{["Name"] = ":balloon:",					["Emoji"] = "🎈"},
	{["Name"] = ":party popper:",				["Emoji"] = "🎉"},
	{["Name"] = ":red envelope:",				["Emoji"] = "🧧"},
	{["Name"] = ":ribbon:",						["Emoji"] = "🎀"},
	{["Name"] = ":wrapped gift:",				["Emoji"] = "🎁"},
	{["Name"] = ":admission tickets:",			["Emoji"] = "🎟"},
	{["Name"] = ":ticket:",						["Emoji"] = "🎫"},
	{["Name"] = ":military medal:",				["Emoji"] = "🎖"},
	{["Name"] = ":trophy:",						["Emoji"] = "🏆"},
	{["Name"] = ":soccer ball:",				["Emoji"] = "⚽"},
	{["Name"] = ":bullseye:",					["Emoji"] = "🎯"},
	{["Name"] = ":water pistol:",				["Emoji"] = "🔫"},
	{["Name"] = ":video game:",					["Emoji"] = "🎮"},
	{["Name"] = ":joystick:",					["Emoji"] = "🕹"},
	{["Name"] = ":slot machine:",				["Emoji"] = "🎰"},
	{["Name"] = ":crystal ball:",				["Emoji"] = "🔮"},
	{["Name"] = ":t-shirt:",					["Emoji"] = "👕"},
	{["Name"] = ":jeans:",						["Emoji"] = "👖"},
	{["Name"] = ":man’s shoe:",					["Emoji"] = "👞"},
	{["Name"] = ":backpack:",					["Emoji"] = "🎒	"},
	{["Name"] = ":crown:",						["Emoji"] = "👑"},
	{["Name"] = ":graduation cap:",				["Emoji"] = "🎓"},
	{["Name"] = ":gem stone:",					["Emoji"] = "💎"},
	{["Name"] = ":loudspeaker:",				["Emoji"] = "📢"},
	{["Name"] = ":bell:",						["Emoji"] = "🔔"},
	{["Name"] = ":musical note	:",				["Emoji"] = "🎵"},
	{["Name"] = ":headphone:",					["Emoji"] = "🎧"},
	{["Name"] = ":battery:",					["Emoji"] = "🔋"},
	{["Name"] = ":laptop:",						["Emoji"] = "💻"},
	{["Name"] = ":desktop computer:",			["Emoji"] = "🖥"},
	{["Name"] = ":floppy disk:",				["Emoji"] = "💾"},
	{["Name"] = ":optical disk	:",				["Emoji"] = "💿"},
	{["Name"] = ":camera:",						["Emoji"] = "📷"},
	{["Name"] = ":magnifying glass tilted left:",["Emoji"] = "🔍"},
	{["Name"] = ":magnifying glass tilted right:",["Emoji"] = "🔎"},
	{["Name"] = ":light bulb:",					["Emoji"] = "💡"},
	{["Name"] = ":red paper lantern:",			["Emoji"] = "🏮"},
	{["Name"] = ":closed book:",				["Emoji"] = "📕"},
	{["Name"] = ":open book:",					["Emoji"] = "📖"},
	{["Name"] = ":page facing up:",				["Emoji"] = "📄"},
	{["Name"] = ":newspaper:",					["Emoji"] = "📰"},
	{["Name"] = ":label:",						["Emoji"] = "🏷"},
	{["Name"] = ":money bag:",					["Emoji"] = "💰"},
	{["Name"] = ":dollar banknote:",			["Emoji"] = "💵"},
	{["Name"] = ":money with wings:",			["Emoji"] = "💸"},
	{["Name"] = ":credit card:",				["Emoji"] = "💳"},
	{["Name"] = ":envelope:",					["Emoji"] = "✉"},
	{["Name"] = ":package:",					["Emoji"] = "📦"},
	{["Name"] = ":briefcase:",					["Emoji"] = "💼"},
	{["Name"] = ":file folder:",				["Emoji"] = "📁	"},
	{["Name"] = ":calendar:",					["Emoji"] = "📅"},
	{["Name"] = ":chart increasing:",			["Emoji"] = "📈"},
	{["Name"] = ":bar chart:",					["Emoji"] = "📊"},
	{["Name"] = ":clipboard:",					["Emoji"] = "📋"},
	{["Name"] = ":pushpin:",					["Emoji"] = "📌"},
	{["Name"] = ":scissors:",					["Emoji"] = "✂"},
	{["Name"] = ":locked:",						["Emoji"] = "🔒"},
	{["Name"] = ":unlocked:",					["Emoji"] = "🔓"},
	{["Name"] = ":key:",						["Emoji"] = "🔑"},
	{["Name"] = ":hammer and wrench:",			["Emoji"] = "🛠"},
	{["Name"] = ":crossed swords:",				["Emoji"] = "⚔"},
	{["Name"] = ":gear:",						["Emoji"] = "⚙"},
	{["Name"] = ":shopping cart:",				["Emoji"] = "🛒"},
	{["Name"] = ":nazar amulet:",				["Emoji"] = "🧿"},
	{["Name"] = ":warning:",					["Emoji"] = "⚠"},
	{["Name"] = ":input latin uppercase:",		["Emoji"] = "🔠"},
}
function emoji:EmojiReplace(str)
	for _,v in pairs(emoji) do
		if string.find(str, v["Name"]) then
			string.gsub(str,v["Name"],v["Emoji"])
		end
	end
	return 
end
return emoji
